export const type = {
  uiOpenModal: '[UI] Open Modal',
  uiCloseModal: '[UI] Close Modal',
  eventAddNew: '[EVENT] Add New',
  eventSetActive: '[EVENT] Set Active',
  eventClearEventActive: '[EVENT] Clean Event Active',
  eventUpdated: '[EVENT] Event Updated',
  eventDeleted: '[EVENT] Event Deleted',
  authChecking: '[AUTH] Checking Login State',
  authCheckingFinish: '[AUTH] Finish Checking Login state',
  authStartLogin: '[AUTH] Start login',
  authLogin:  '[AUTH] login', 
  authStartRegister:  '[AUTH] Start Register', 
  authStartTokenRenew:  '[AUTH] Start Token Renew', 
  authLogout:  '[AUTH] Logout', 
}